add_header                  Strict-Transport-Security "max-age=63072000; includeSubdomains; ";
add_header                  X-Frame-Options SAMEORIGIN;
add_header                  X-Content-Type-Options nosniff;
add_header                  Referrer-Policy 'same-origin';
add_header                  X-XSS-Protection "1; mode=block";
# add_header                  Content-Security-Policy "script-src 'self'";
